name: MacOS 12.6 Monterey x86-64 Compile

on: [push,workflow_dispatch,workflow_call]

jobs:
  build:

    runs-on: macos-12

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Compile OpenSSL
        run: |
          export NONINTERACTIVE=1
          brew install ninja secp256k1 libsodium libmicrohttpd pkg-config automake libtool
          git clone https://github.com/openssl/openssl openssl_1_1_1
          cd openssl_1_1_1
          git checkout OpenSSL_1_1_1-stable
          ./Configure darwin64-x86_64-cc -static -mmacosx-version-min=12.6
          make build_libs -j4

      - name: Compile Secp256k1
        run: |
          git clone https://github.com/libbitcoin/secp256k1.git
          cd secp256k1
          ./autogen.sh
          ./configure --enable-module-recovery
          make
          make install

      - name: Build all
        run: |
          brew unlink openssl@3
          rootPath=`pwd`
          mkdir build
          cd build
          cmake -GNinja -DOPENSSL_FOUND=1 -DOPENSSL_INCLUDE_DIR=$rootPath/openssl_1_1_1/include -DOPENSSL_CRYPTO_LIBRARY=$rootPath/openssl_1_1_1/libcrypto.a -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=12.6 -DCMAKE_CXX_FLAGS="-stdlib=libc++" -DCMAKE_BUILD_TYPE=Release ..
          ninja storage-daemon storage-daemon-cli blockchain-explorer fift func tonlib tonlibjson tonlib-cli validator-engine lite-client pow-miner validator-engine-console generate-random-id json2tlo dht-server http-proxy rldp-http-proxy adnl-proxy create-state create-hardfork tlbc emulator

      - name: Strip binaries
        run: |          
          strip build/storage/storage-daemon/storage-daemon
          strip build/storage/storage-daemon/storage-daemon-cli
          strip build/blockchain-explorer/blockchain-explorer
          strip build/crypto/fift
          strip build/crypto/func
          strip build/crypto/create-state
          strip build/crypto/tlbc
          strip build/validator-engine-console/validator-engine-console 
          strip build/tonlib/tonlib-cli
          strip build/http/http-proxy
          strip build/rldp-http-proxy/rldp-http-proxy
          strip build/dht-server/dht-server
          strip build/lite-client/lite-client
          strip build/validator-engine/validator-engine
          strip build/utils/generate-random-id
          strip build/utils/json2tlo
          strip build/adnl/adnl-proxy

      - name: Find & copy binaries
        run: |
          mkdir artifacts
          cp build/storage/storage-daemon/storage-daemon artifacts/
          cp build/storage/storage-daemon/storage-daemon-cli artifacts/
          cp build/blockchain-explorer/blockchain-explorer artifacts/
          cp build/crypto/fift artifacts/
          cp build/crypto/func artifacts/
          cp build/crypto/create-state artifacts/
          cp build/crypto/tlbc artifacts/
          cp build/validator-engine-console/validator-engine-console artifacts/ 
          cp build/tonlib/tonlib-cli artifacts/
          cp build/tonlib/libtonlibjson.0.5.dylib artifacts/libtonlibjson.dylib 
          cp build/http/http-proxy artifacts/
          cp build/rldp-http-proxy/rldp-http-proxy artifacts/
          cp build/dht-server/dht-server artifacts/
          cp build/lite-client/lite-client artifacts/
          cp build/validator-engine/validator-engine artifacts/
          cp build/utils/generate-random-id artifacts/
          cp build/utils/json2tlo artifacts/
          cp build/adnl/adnl-proxy artifacts/
          cp build/emulator/*emulator.* artifacts/
          chmod +x artifacts/*
          rsync -r crypto/smartcont artifacts/
          rsync -r crypto/fift/lib artifacts/
          ls -laRt artifacts

      - name: Simple binaries test
        run: |
          artifacts/validator-engine -V
          artifacts/lite-client -V
          artifacts/fift -V
          artifacts/func -V

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: ton-macos-12.6
          path: artifacts
