name: "TON x86_64 Linux binaries"

on: [push,workflow_dispatch,workflow_call]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - run: |
        sudo apt update
        sudo apt install -y apt-utils 

    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Compile
      run: nix build .?submodules=1#packages.x86_64-linux.ton-oldglibc_staticbinaries --print-build-logs --system x86_64-linux -o result-x86_64

    - name: Copy binaries
      run: |
        ls -lart 
        mkdir artifacts
        cp $PWD/result-x86_64/bin/* artifacts/
        chmod +x artifacts/*
        cp $PWD/result-x86_64/lib/libtonlibjson.so.0.5 artifacts/
        cp -R crypto/smartcont artifacts/
        cp -R crypto/fift/lib artifacts/

    - name: Simple binaries test
      run: |
        sudo mv /nix/store /nix/store2
        artifacts/validator-engine -V
        artifacts/lite-client -V
        artifacts/fift -V
        artifacts/func -V

    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: ton-x86_64-linux-binaries
        path: artifacts